<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TrabajadorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('trabajador')->insert([
        ['paterno' => 'García',
                'materno' => 'López',
                'primer' => 'Juan',
                'segundo' => 'Carlos',
                'id_tipo_documento' => 1, // Asumiendo que 1 es DNI
                'numero_documento' => '12345678',
                'fecha_nacimiento' => '1990-05-15',
                'ruc' => '10123456789',
                'direccion' => 'Av. Los Álamos 123',
                'referencia' => 'Cerca al parque central',
                'id_ubigeo' => 1, // Asumiendo que 1 es Lima
                'telefono' => '01234567',
                'celular' => '987654321',
                'correo' => 'juan.garcia@example.com',
                'id_empleador' => 3,
                'id_regimen_laboral' => 1,
                'id_ocupacion' => 1,
                'id_tipo_contrato' => 1,
                'id_cargo' => 1,
                'id_area' => 1,
                'es_jefe' => true,
                'id_jornada_laboral' => 1,
                'id_estado_trabajador' => 1,
                'fecha_estado' => '2023-01-01',
                'id_nivel_educativo' => 1,
                'id_regimen_salud' => 1,
                'id_regimen_pensiones' => 1,
                'id_afp' => 1,
                'cuspp' => '123456ABCDEF',
                'es_discapacitado' => false,
                'es_sindicalizado' => false,
                'fecha_ingreso' => '2023-01-01',
                'fecha_egreso' => '2021-01-01',
                'id_motivo_baja' => 1,
                'fecha_baja' => '2024-01-01',
                'id_contrato' => 1,
                'aprueba_solicitudes' => true,
                'saldo_inicial_vacaciones' => 15.00,
                'id_user' => 4,
                'created_at' => now(),
                'updated_at' => now(),],
        ['paterno' => 'Rodríguez',
                'materno' => 'Martínez',
                'primer' => 'María',
                'segundo' => 'Isabel',
                'id_tipo_documento' => 1, // Asumiendo que 1 es DNI
                'numero_documento' => '87654321',
                'fecha_nacimiento' => '1985-10-20',
                'ruc' => '10987654321',
                'direccion' => 'Jr. Las Palmeras 456',
                'referencia' => 'Frente al centro comercial',
                'id_ubigeo' => 2, // Asumiendo que 2 es otra ciudad
                'telefono' => '01765432',
                'celular' => '912345678',
                'correo' => 'maria.rodriguez@example.com',
                'id_empleador' => 2,
                'id_regimen_laboral' => 1,
                'id_ocupacion' => 2,
                'id_tipo_contrato' => 1,
                'id_cargo' => 2,
                'id_area' => 2,
                'es_jefe' => false,
                'id_jornada_laboral' => 1,
                'id_estado_trabajador' => 1,
                'fecha_estado' => '2023-02-01',
                'id_nivel_educativo' => 2,
                'id_regimen_salud' => 1,
                'id_regimen_pensiones' => 1,
                'id_afp' => 2,
                'cuspp' => '654321FEDCBA',
                'es_discapacitado' => false,
                'es_sindicalizado' => true,
                'fecha_ingreso' => '2023-01-01',
                'fecha_egreso' => '2021-01-01',
                'id_motivo_baja' => 1,
                'fecha_baja' => '2024-01-01',
                'id_contrato' => 2,
                'aprueba_solicitudes' => false,
                'saldo_inicial_vacaciones' => 10.00,
                'id_user' => 5,
                'created_at' => now(),
                'updated_at' => now(),],
                [
    'paterno' => 'Fernández',
    'materno' => 'Martínez',
    'primer' => 'Luis',
    'segundo' => 'Alberto',
    'id_tipo_documento' => 2, // Asumiendo que 2 es pasaporte
    'numero_documento' => '87654321',
    'fecha_nacimiento' => '1988-08-10',
    'ruc' => '10456789123',
    'direccion' => 'Jr. Las Rosas 456',
    'referencia' => 'Frente al colegio nacional',
    'id_ubigeo' => 2, // Asumiendo que 2 es Arequipa
    'telefono' => '02345678',
    'celular' => '912345678',
    'correo' => 'luis.fernandez@example.com',
    'id_empleador' => 3,
    'id_regimen_laboral' => 1,
    'id_ocupacion' => 2,
    'id_tipo_contrato' => 2,
    'id_cargo' => 2,
    'id_area' => 2,
    'es_jefe' => false,
    'id_jornada_laboral' => 2,
    'id_estado_trabajador' => 2,
    'fecha_estado' => '2023-02-01',
    'id_nivel_educativo' => 2,
    'id_regimen_salud' => 2,
    'id_regimen_pensiones' => 2,
    'id_afp' => 2,
    'cuspp' => '987654ZYXWVU',
    'es_discapacitado' => true,
    'es_sindicalizado' => false,
    'fecha_ingreso' => '2023-02-01',
    'fecha_egreso' => null,
    'id_motivo_baja' => null,
    'fecha_baja' => null,
    'id_contrato' => 2,
    'aprueba_solicitudes' => false,
    'saldo_inicial_vacaciones' => 20.00,
    'id_user' => 6,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'paterno' => 'Ramírez',
    'materno' => 'Gómez',
    'primer' => 'María',
    'segundo' => 'Elena',
    'id_tipo_documento' => 1, // Asumiendo que 1 es DNI
    'numero_documento' => '45678912',
    'fecha_nacimiento' => '1995-03-22',
    'ruc' => '10567891234',
    'direccion' => 'Calle Las Magnolias 789',
    'referencia' => 'A una cuadra del centro comercial',
    'id_ubigeo' => 1, // Asumiendo que 1 es Lima
    'telefono' => '03456789',
    'celular' => '987654123',
    'correo' => 'maria.ramirez@example.com',
    'id_empleador' => 2,
    'id_regimen_laboral' => 2,
    'id_ocupacion' => 1,
    'id_tipo_contrato' => 1,
    'id_cargo' => 1,
    'id_area' => 1,
    'es_jefe' => false,
    'id_jornada_laboral' => 1,
    'id_estado_trabajador' => 1,
    'fecha_estado' => '2023-03-01',
    'id_nivel_educativo' => 1,
    'id_regimen_salud' => 1,
    'id_regimen_pensiones' => 1,
    'id_afp' => 1,
    'cuspp' => '456789QWERTY',
    'es_discapacitado' => false,
    'es_sindicalizado' => true,
    'fecha_ingreso' => '2023-03-01',
    'fecha_egreso' => '2023-10-01',
    'id_motivo_baja' => 2,
    'fecha_baja' => '2023-10-15',
    'id_contrato' => 1,
    'aprueba_solicitudes' => true,
    'saldo_inicial_vacaciones' => 10.00,
    'id_user' => 7,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'paterno' => 'Vega',
    'materno' => 'Rojas',
    'primer' => 'Carlos',
    'segundo' => 'Andrés',
    'id_tipo_documento' => 1, // Asumiendo que 1 es DNI
    'numero_documento' => '11223344',
    'fecha_nacimiento' => '1992-11-18',
    'ruc' => '10654321098',
    'direccion' => 'Av. Las Palmeras 101',
    'referencia' => 'Junto al hospital regional',
    'id_ubigeo' => 2, // Asumiendo que 2 es Arequipa
    'telefono' => '04567890',
    'celular' => '923456789',
    'correo' => 'carlos.vega@example.com',
    'id_empleador' => 3,
    'id_regimen_laboral' => 1,
    'id_ocupacion' => 1,
    'id_tipo_contrato' => 2,
    'id_cargo' => 1,
    'id_area' => 2,
    'es_jefe' => true,
    'id_jornada_laboral' => 1,
    'id_estado_trabajador' => 1,
    'fecha_estado' => '2023-04-01',
    'id_nivel_educativo' => 1,
    'id_regimen_salud' => 2,
    'id_regimen_pensiones' => 2,
    'id_afp' => 1,
    'cuspp' => '321654LMNOPQ',
    'es_discapacitado' => false,
    'es_sindicalizado' => false,
    'fecha_ingreso' => '2023-04-01',
    'fecha_egreso' => null,
    'id_motivo_baja' => null,
    'fecha_baja' => null,
    'id_contrato' => 2,
    'aprueba_solicitudes' => true,
    'saldo_inicial_vacaciones' => 12.00,
    'id_user' => 8,
    'created_at' => now(),
    'updated_at' => now(),
],

                
    ]);
    }
}
